FROM node:18-alpine as build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
#ARG REACT_APP_BASE_URL
#ENV REACT_APP_BASE_URL=$REACT_APP_BASE_URL
ENV REACT_APP_BASE_URL=http://127.0.0.1
ENV REACT_APP_BASE_PORT=5001
RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html