FROM node:18-alpine
ENV NODE_ENV development
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ENV REACT_APP_BASE_ADRESS="http://127.0.0.1"
ENV REACT_APP_BASE_PORT=5001
EXPOSE 3000
CMD ["npm", "start"]