FROM node:18-alpine as build
ENV NODE_ENV production
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ARG BASE_ADRESS
ENV REACT_APP_BASE_ADRESS=$BASE_ADRESS
ENV REACT_APP_BASE_PORT=5001
RUN npm run build -p

FROM nginx:mainline-alpine
COPY --from=build /app/build /usr/share/nginx/html