FROM node:18-alpine as build
ENV NODE_ENV development
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ENV REACT_APP_BASE_ADRESS="http://127.0.0.1"
ENV REACT_APP_BASE_PORT=5001
EXPOSE 3000
CMD ["npm", "start"]

#FROM nginx:mainline-alpine
#COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf