version: '3.8'
services:
  nginx:
    platform: linux
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    platform: linux/amd64
    environment:
      - DB_URL=mongodb://mongodbuser:Zs24pS3IrU8rNRWAuZtWUx@95.216.198.114:27017/supplier4?authSource=admin
      - PORT=5001
      - JWT_SECRET=pQe%06Wl8a05
    build:
      context: ./Server
      dockerfile: Dockerfile.prod
    container_name: supplier.server
    ports:
      - '5001:5001'
    volumes:
      - /app/node_modules
      - ./Server:/app
#      - /app/assets
    stdin_open: true
    tty: true

  client:
    platform: linux/amd64
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASE_ADRESS="http://localhost"
    depends_on:
      - api
    build:
      context: ./Client
      dockerfile: Dockerfile.prod
    container_name: supplier.client
    ports:
      - '80:80'
    volumes:
      - /app/node_modules
      - ./Client:/app
    stdin_open: true
    tty: true