version: '3.8'
services:
  api:
    platform: linux/amd64
    build:
      context: ./Server
    container_name: supplier.server
#    image: arf535/supplier.server
    ports:
      - '5001:5001'
    volumes:
      - ./docker:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
  client:
    platform: linux/amd64
    build:
      context: ./Client
    container_name: supplier.client
#    image: arf535/supplier.client
    ports:
      - '3000:3000'
    volumes:
      - ./Client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
