version: '3.8'
services:
  api:
    platform: linux/amd64
    build:
      context: ./Server
      dockerfile: Dockerfile.dev
    container_name: supplier.server
    ports:
      - '5001:5001'
    volumes:
      - ./app/node_modules
      - ./Server:/app
    #      - ./docker:/app
    stdin_open: true
    tty: true
  client:
    platform: linux/amd64
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./Client
      dockerfile: Dockerfile.dev
    container_name: supplier.client
    ports:
      - '3000:3000'
    volumes:
      - ./app/node_modules
      - ./Client:/app
    stdin_open: true
    tty: true
