version: '3.8'
services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=supplier
      - MONGO_INITDB_ROOT_USERNAME=mongodbuser
      - MONGO_INITDB_ROOT_PASSWORD=Zs24pS3IrU8rNRWAuZtWUx
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - network

  api:
    image: arf535/supplier.server:latest
    platform: linux/amd64
    environment:
      - DB_URL=mongodb://mongodbuser:Zs24pS3IrU8rNRWAuZtWUx@mongo:27017/supplier?authSource=admin
      - PORT=5001
      - JWT_SECRET=pQe%06Wl8a05
    networks:
      - network
    depends_on:
      - mongo
    build:
      context: ./Server
      dockerfile: Dockerfile.prod
    container_name: supplier.server
    restart: unless-stopped
    volumes:
      - server_node_modules:/app/node_modules
      - photo:/app/public/assets
    stdin_open: true
    tty: true

  client:
    image: arf535/supplier.client:latest
    platform: linux/amd64
    environment:
      - CHOKIDAR_USEPOLLING=true
      - BASE_ADRESS="http://localhost"
    networks:
      - network
    depends_on:
      - api
    build:
      context: ./Client
      dockerfile: Dockerfile.prod
    container_name: supplier.client
    restart: unless-stopped
    volumes:
      - web-root:/usr/share/nginx/html
      - web-config:/etc/nginx/conf.d
      - photo:/var/www/app/assets
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    stdin_open: true
    tty: true
    ports:
      - "80:80"
      - "443:443"

#  certbot:
#    image: certbot/certbot
#    container_name: certbot
#    volumes:
#      - certbot-etc:/etc/letsencrypt
#      - certbot-var:/var/lib/letsencrypt
#      - web-root:/usr/share/nginx/html
#    depends_on:
#      - webserver
#      - api
#      - client
#    networks:
#      - network
#    command: certonly --webroot --webroot-path=/usr/share/nginx/html/ --email arf@deskit.ru --agree-tos --no-eff-email --staging -d dev.deskit.ru  -d www.dev.deskit.ru
#    command: certonly --webroot --webroot-path=/usr/share/nginx/html/ --email arf@deskit.ru --agree-tos --no-eff-email --force-renewal -d dev.deskit.ru  -d www.dev.deskit.ru

volumes:
  certbot-etc:
  certbot-var:
  web-config:
  web-root:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: ~/dhparam/
      o: bind
  server_node_modules:
  photo:
  mongodb:
  mongoconfig:

networks:
  network:
    driver: bridge