version: '3.8'
services:
  nginx:
    platform: linux
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    platform: linux/amd64
    environment:
      - DB_URL=mongodb://mongodbuser:<password>@<ip>:<port>/<db_name>?authSource=admin
      - PORT=5001
      - JWT_SECRET=pQe%06Wl8a05
    image: arf535/supplier.server
    container_name: supplier.server
    ports:
      - '5001:5001'
    volumes:
      - /app/node_modules
      - ./Server:/app
    stdin_open: true
    tty: true

  client:
    platform: linux/amd64
    depends_on:
      - api
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASE_URL="http://127.0.0.1:5001/"
    image: arf535/supplier.client
    container_name: supplier.client
    ports:
      - '80:80'
    volumes:
      - /app/node_modules
      - ./Client:/app
    stdin_open: true
    tty: true