FROM node:18-alpine as build
#RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ARG DB_URL
ARG PORT
ARG JWT_SECRET
ENV DB_URL=$DB_URL
ENV PORT=$PORT
ENV JWT_SECRET=$JWT_SECRET
RUN npm i
CMD ["npm", "run", "start"]