FROM node:18-alpine
RUN npm install -g nodemon
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ARG env_DB_URL
ENV DB_URL=$DB_URL
ARG PORT
ENV PORT=$PORT
ARG JWT_SECRET
ENV JWT_SECRET=$JWT_SECRET
EXPOSE 5001
CMD ["npm", "run", "dev"]